#int32 time

# Raw sensor values.
float32 led0raw
float32 led1raw
float32 led2raw
float32 led3raw
float32 led4raw
float32 led5raw

# Filtered sensor values.
float32 led0filtered
float32 led1filtered
float32 led2filtered
float32 led3filtered
float32 led4filtered
float32 led5filtered

# Rotation data
#float32[3] rotationVector

# Motor values
float32 motorT
float32 motorR
float32 motorL

# PID gains for X, Y, Z axes.
float32 P
float32 I
float32 D

# Loop time
#int32 looptime

